biocore/microsetta-public-api

README.md, microsetta_public_api/api/diversity/alpha.py, microsetta_public_api/api/microsetta_public_api.yml, microsetta_public_api/api/tests/test_api.py, microsetta_public_api/models/_alpha.py, microsetta_public_api/models/_base.py, microsetta_public_api/models/tests/test_alpha.py, microsetta_public_api/repo/_alpha_repo.py
Summary of changes:
* `README.md`
* small fix
* `microsetta_public_api/api/diversity/alpha.py`
* Replaced placeholder function with a function that matches the OpenAPI spec better
* `microsetta_public_api/repo/_alpha_repo.py`
* Added. In the future, this should be the place where alpha diversity is obtained from the backend.
* `microsetta_public_api/models/_alpha.py`
* change `metric` to `alpha_metric` to better reflect API spec
* `microsetta_public_api/api/microsetta_public_api.yml`
* change `value` to `data` to better be forward compatible with array of alpha diversity (next milestone)
* `microsetta_public_api/api/tests/test_api.py`
* Mock the return value from `AlphaRepo`
* Reflect `value` to `data` change
* Assert that we get a 404 error if there is an UnkownID
=> Single sample alpha implementation

microsetta_public_api/api/diversity/alpha.py, microsetta_public_api/api/microsetta_public_api.yml, microsetta_public_api/api/tests/test_api.py, microsetta_public_api/models/_alpha.py, microsetta_public_api/models/tests/test_alpha.py, microsetta_public_api/repo/_alpha_repo.py
Summary of major changes:
* Added a `POST` for `/diversity/alpha_group/{alpha_metric}` that should allow you to post a JSON that will allow you to request the alpha diversity for samples that you specify
* Added `microsetta_public_api.diversity.alpha_group` which parses the request and prepares a response for the above POST.
* changed a field `diversity` to `alpha_diversity` to be more explicit.
=> First draft of group alpha retrieval

microsetta_public_api/api/diversity/alpha.py, microsetta_public_api/api/diversity/tests/test_alpha.py, microsetta_public_api/api/microsetta_public_api.yml, microsetta_public_api/api/tests/test_api.py, microsetta_public_api/models/_alpha.py, microsetta_public_api/utils/testing.py, microsetta_public_api/utils/tests/test_utils.py
This one got a bit of scope creep in the tests 😅 
This PR adds Alpha diversity group summaries into the REST API, as well as some testing utilities and improved separation of the API and implementation layers in testing of `alpha_group`.
The major API changes (open to more consideration) include:
* Adding ability to return group summaries from `/api/diversity/alpha_group/{alpha_metric}`
* As it is currently written, a user can ask for raw values, a summary, or both (with option to change percentiles in summary). 
* Posts that ask for neither raw values or a summary (e.g., `/api/diversity/alpha_group/{alpha_metric}?return_raw=false&summary_statistics=false`) will give a bad request error.
* By default, summary statistics will be returned and raw values will not be.
=> Expose alpha summary statistics

.gitignore, README.md, microsetta_public_api/api/__init__.py, microsetta_public_api/api/diversity/alpha.py, microsetta_public_api/api/diversity/tests/test_alpha.py, microsetta_public_api/api/microsetta_public_api.yml, microsetta_public_api/api/taxonomy.py, microsetta_public_api/api/tests/implementation_tests/test_taxonomy.py, microsetta_public_api/api/tests/test_api.py, microsetta_public_api/api/tests/test_integration.py, microsetta_public_api/config.py, microsetta_public_api/models/tests/test_taxonomy.py, microsetta_public_api/repo/_alpha_repo.py, microsetta_public_api/repo/_taxonomy_repo.py, microsetta_public_api/repo/tests/test_alpha_repo.py, microsetta_public_api/repo/tests/test_taxonomy_repo.py, microsetta_public_api/resources.py, microsetta_public_api/tests/test_resources.py, microsetta_public_api/utils/__init__.py, microsetta_public_api/utils/_utils.py, microsetta_public_api/utils/testing.py
This PR adds the full fledged taxonomy feature to the API.
It basically exposes the `Taxonomy.get_group` function the the API.
There is support for adding both Q2 FeatureTables and biom tables, along with `FeatureData[Taxonomy]` to the server.
There is also a ton of testing to go along with these changes, some modularity improvements, and a number of utility updates.
=> Taxonomy implementation

README.md, microsetta_public_api/resources.py, microsetta_public_api/tests/test_resources.py, microsetta_public_api/utils/testing.py
This PR serves to add the ability to configure metadata to add to the server.
By adding a
```
{
...
'metadata': '/some/system/path.txt'
...
}
```
keyword to the config, with the path referring to some QIIME2 formatted metadata file, you can add a single metadata file to the server.
=> Add metadata resources

microsetta_public_api/resources.py, microsetta_public_api/tests/test_resources.py
This PR allows us to ignore predicates, such as the ` % Properties('phylogenetic')` in `SampleData[AlphaDiversity]` when validating Q2 artifacts. This is the new default for now. This was creating issues when trying to add a Faith's PD artifact to my local dev server.
=> BUG add ability to ignore predicates in q2 type checking

microsetta_public_api/repo/_metadata_repo.py, microsetta_public_api/repo/tests/test_metadata_repo.py
This PR adds the metadata repo, used for finding out information about the metadata, including filtering for sample ids that meet certain criteria.
Note that the `query` parameter taken by `MetadataRepo.sample_id_matches` is expected to be approximately of the form output by [jQuery QueryBuilder](https://querybuilder.js.org/). This should hopefully withstand some amount of forward compatibility, but could easily be dropped for a simpler approach.
Also note that this PR branch builds on #13 so some changes will be repeats.
=> Metadata repo for age cat bmi queries

microsetta_public_api/api/metadata.py, microsetta_public_api/api/microsetta_public_api.yml, microsetta_public_api/api/tests/test_api.py, microsetta_public_api/utils/testing.py
This PR includes a draft of the swagger yaml and tests for responses that should allow for API calls like:
```
GET …/metadata/category/values/age_cat
```
which would return something like “20s, 30s, 40s…”, the specific values of the category
and
```
GET …/metadata/sample-ids/age_cat=<a-specific-value>&bmi_cat=<a-specific-value>
```
which would return the sample ids that meet the age and bmi criteria
=> Add REST endpoints for filtering samples in metadata by age and BMI

microsetta_public_api/api/metadata.py, microsetta_public_api/api/microsetta_public_api.yml, microsetta_public_api/api/tests/implementation_tests/test_metadata.py, microsetta_public_api/api/tests/test_api.py, microsetta_public_api/api/tests/test_integration.py
Adds a feature for filtering the sample ids in the metadata by a given table with taxonomy and/or alpha metric data.
=> Metadata filter sample ids by taxonomy and alpha

microsetta_public_api/api/microsetta_public_api.yml, microsetta_public_api/api/tests/test_api.py, microsetta_public_api/api/tests/test_integration.py
This PR serves to unify to provide a more consistent interface with the API. This entails the following path changes:
And the following refactoring of snake case to camel case in the swagger schemas, to reflect more typical swagger convention for schemas:
=> MAINT Refactor alpha, taxonomy, and metadata for consitstency/convention

microsetta_public_api/api/tests/test_integration.py, microsetta_public_api/repo/_metadata_repo.py, microsetta_public_api/repo/tests/test_metadata_repo.py
Found this while working with the microsetta metadata.
`NaN` values are not really allowed in JSON format, but python's `json.dump` (exposed via flask) will go ahead and [serialize them anyways](https://stackoverflow.com/questions/6601812/sending-nan-in-json/6601873)... So I added a flag to the metadata repo that allows you to filter them. This was causing problems in javascript when it tried to parse the JSON and got errors on trying to deserialize `Nan`.
The alternative solution was mapping the `NaN` to `None` or some sentinel value, though this PR does not preclude those types of solutions.
=> BUG filter na values from metadata category values

microsetta_public_api/api/metadata.py, microsetta_public_api/api/tests/test_integration.py
Fixes #25 .
I was able to identify bad `alpha_metric` and `taxonomy` values in `"GET /api/metadata/sample_ids"` as a source of this bug. When the values did not exist on the server, `flask.jsonify` would be called on a `flask.Response` object, causing this error.
This PR adds tests that expose the bug and a fix.
It was not observed in the previous implementation tests, presumably due to differences between `flask`'s `Response` object and my `MockedResponse`, which is used in the metadata implementation unit tests. Integration tests helped resolve this discrepancy.
=> Fix metadata 500 error

README.md, microsetta_public_api/api/taxonomy.py, microsetta_public_api/api/tests/implementation_tests/test_taxonomy.py, microsetta_public_api/api/tests/test_integration.py, microsetta_public_api/repo/_taxonomy_repo.py, microsetta_public_api/repo/tests/test_taxonomy_repo.py, microsetta_public_api/resources.py, microsetta_public_api/tests/test_resources.py
Fixes #26 
This PR adds a `cache-taxonomy` keyword to the server config, which can be used to create the model a single time on server start (or subsequent update of the resources).
The default value is currently false, unless otherwise specified.
=> Cache taxonomy model (optional, defaults to true, recommended for large datasets)

microsetta_public_api/api/microsetta_public_api.yml, microsetta_public_api/api/taxonomy.py, microsetta_public_api/api/tests/test_api.py
Adds an endpoint (no implementation) for a taxonomy summary that should be more compatible with the jQuery DataTable as detailed [here](https://datatables.net/reference/option/columns.data). As mentioned in #27
=> API add datatable compatible endpoint for taxonomy

microsetta_public_api/api/taxonomy.py, microsetta_public_api/api/tests/implementation_tests/test_taxonomy.py, microsetta_public_api/api/tests/test_integration.py, microsetta_public_api/models/_taxonomy.py, microsetta_public_api/models/tests/test_taxonomy.py, microsetta_public_api/utils/__init__.py, microsetta_public_api/utils/_utils.py, microsetta_public_api/utils/tests/test_utils.py
Fixes #27 . Implements #33 .
This adds the guts for the new taxonomy endpoint. Has potential for forward compatibility with differing taxonomy formats.
Also introduces a `DataTable` class and `create_data_entry` utility that should hopefully aid future development of endpoints that rely on formatting a js DataTable.
=> Jquery datable compatible taxonomy endpoint implementation

microsetta_public_api/api/diversity/beta.py, microsetta_public_api/api/emperor.py, microsetta_public_api/api/metadata.py, microsetta_public_api/api/microsetta_public_api.yml, microsetta_public_api/api/plotting.py, microsetta_public_api/api/tests/test_api.py
This PR adds the following endpoints in the API spec (with corresponding tests), which will be helpful for a participant interface:
- `POST /metadata/sample_ids`
- method: `microsetta_public_api.api.metadata.filter_sample_ids_query_builder`
- `GET /plotting/diversity/alpha/{alpha_metric}/percentiles-plot`
- method: `microsetta_public_api.api.plotting.plot_alpha_filtered`
- `POST /plotting/diversity/alpha/{alpha_metric}/percentiles-plot`
- method: `microsetta_public_api.api.plotting.plot_alpha_filtered_json_query`
- `GET /diversity/beta/pcoa/contains/{beta_metric}/{named_sample_set}/{sample_id}`
- method: `microsetta_public_api.api.diversity.beta.pcoa_contains`
- `GET /plotting/diversity/beta/pcoa/{beta_metric}/{named_sample_set}`
- method: `microsetta_public_api.api.plotting.plot_beta`
- …
=> Add endpoints from initial interface demo

microsetta_public_api/api/metadata.py, microsetta_public_api/api/microsetta_public_api.yml, microsetta_public_api/api/tests/implementation_tests/test_metadata.py, microsetta_public_api/api/tests/test_integration.py
Depends on #37 
This PR adds the underlying functionality and associated unit tests for processing sample ID queries on metadata, received in the format of [jQuery QueryBuilder](https://querybuilder.js.org/). This will be helpful for adding nice query boxes, e.g below, to a user interface:
=> Add querybuilder metadata implementation

microsetta_public_api/models/_taxonomy.py
Fixes #42 
A major source of the slowdown and memory consumption was the creation of `_variances` in the taxonomy model, which used a full dense `np.array` of zeros to create a `biom.Table`. This can easily be replaced by a sparse equivalent, which reduces time/memory.
=> Use scipy.sparse on empty variance construction

microsetta_public_api/server.py, microsetta_public_api/utils/testing.py, microsetta_public_api/utils/tests/test_utils.py
Adds a utility for creating test databases on the fly. This could be used to create a database of arbitrary size, for stress-testing, or other similar purposes.
=> UTIL adds a utility class for a randomizable test database

ci/test-env.yml, microsetta_public_api/server.py, setup.py
We found in local testing that we need the api to send back Access-Control-Allow-Origin headers, flask-cors does this.
=> Adds CORS with flask-cors, you need this for local testing.

MANIFEST.in, microsetta_public_api/config.py, microsetta_public_api/server.py, microsetta_public_api/server_config.json, setup.py
Now using a similar config mechanism to the other microsetta- projects. This is helpful particularly for deployments via gunicorn where (on the other projects) we are not utilizing `sys.argv`
=> More closely mirror config handling for other microsetta- projects

microsetta_public_api/server.py, microsetta_public_api/server_config.json, microsetta_public_api/tests/test_server.py
Resources are pulled directly from config on build_app, and `run` is now via an indirection. This is critical for the current deployment which does not use `__main__`
=> run indirection

microsetta_public_api/api/diversity/alpha.py, microsetta_public_api/api/diversity/tests/test_alpha.py, microsetta_public_api/api/microsetta_public_api.yml, microsetta_public_api/api/tests/test_api.py, microsetta_public_api/api/tests/test_integration.py
This PR adds a mechanism for including samples that match metadata queries in alpha diversity group summaries.
A metadata query can be posted in addition to an array of sample ID's, or on its own.
If both are added, then a `condition` must be specified, which indicates whether the union or intersection of posted IDs and metadata-matched ID's should be returned.
=> NEW add metadata query to alpha group

microsetta_public_api/server.py, microsetta_public_api/utils/testing.py
This fixes some small bugs.
1) The `TestDatabase` context manager was exiting immediately. I solved this by adding a `start` and `stop` for the test database that construct the TestDatabase and deconstruct it, previously occuring in `__enter__` and `__exit__`.
2) There was an uncaught `UnknownMetric` exception resulting in a 500 error on calls to the server. I fixed it by add an error handler to the flask app. I would like to work toward implementing this pattern in general for 404's and such.
=> BUG fix uncaught missing metric and fix TestDatabase start

microsetta_public_api/api/diversity/alpha.py, microsetta_public_api/api/diversity/beta.py, microsetta_public_api/api/emperor.py, microsetta_public_api/api/metadata.py, microsetta_public_api/api/microsetta_public_api.yml, microsetta_public_api/api/plotting.py, microsetta_public_api/api/taxonomy.py
This PR adds endpoints for "named datasets" which should allow querying separate alpha/beta/taxonomy/pcoa structures, such as one for 16S Amplicon Sequencing and one for Shotgun metagenomics data, or even some kind of endpoints for qRT-PCR.
Basically duplicates every endpoint except metadata endpoints, and adds a name argument for the dataset.
=> Named dataset endpoint

microsetta_public_api/api/datasets.py, microsetta_public_api/api/metadata.py, microsetta_public_api/api/microsetta_public_api.yml, microsetta_public_api/api/tests/implementation_tests/test_datasets.py, microsetta_public_api/api/tests/implementation_tests/test_metadata.py, microsetta_public_api/api/tests/test_api.py, microsetta_public_api/api/tests/test_integration.py
Adds two new endpoints, `/metadata/category/available` and `/avaialable/dataset` that list the available metadata categories and available datasets, respectively.
=> List metadata available categories and available datasets

microsetta_public_api/api/metadata.py, microsetta_public_api/api/microsetta_public_api.yml, microsetta_public_api/api/tests/implementation_tests/test_metadata.py, microsetta_public_api/api/tests/test_api.py, microsetta_public_api/exceptions.py, microsetta_public_api/server.py
Fixes #65 
This piece allows for metadata about specific sample ID's to be queried.
=> NEW endpoint for querying metadata given sample ID's

microsetta_public_api/api/diversity/beta.py, microsetta_public_api/api/diversity/tests/test_beta.py, microsetta_public_api/api/microsetta_public_api.yml, microsetta_public_api/api/tests/test_api.py, microsetta_public_api/api/tests/test_integration.py, microsetta_public_api/utils/testing.py
This support connects the `k` nearest functionality of `BetaRepo` to the Flask API.
=> Add k nearest api

microsetta_public_api/exceptions.py, microsetta_public_api/models/_taxonomy.py, microsetta_public_api/models/tests/test_taxonomy.py
Processing for WGS data right is not explicitly filtering the taxonomy data to only the features present. This is preferred as it would be a specific need for WGS in the shotgun processing rather than general. For 16S  processing, we only obtain taxonomy for the features present whereas for shotgun we just use the existing Woltka taxonomy mapping file.
=> Allow taxonomy features to be superset of abundance table

microsetta_public_api/api/microsetta_public_api.yml, microsetta_public_api/api/taxonomy.py, microsetta_public_api/api/tests/implementation_tests/test_taxonomy.py, microsetta_public_api/api/tests/test_api.py, microsetta_public_api/models/_taxonomy.py, microsetta_public_api/models/tests/test_taxonomy.py, microsetta_public_api/resources.py
Addresses #72.
A few notes:
- for caching, it is advantageous to limit to the top few taxa upfront to keep the overall data small (and plotting is oriented around the top few not everything)
- there was a `feature_ranks` attribute, but I don't think it was actually being used, and I'll remove it in coming commits
- not attached to endpoints yet
- I think we want to just limit this to a particular taxonomic rank right now, and can expand in the future if we need
=> Initial rank support

microsetta_public_api/api/tests/implementation_tests/test_taxonomy.py, microsetta_public_api/models/_taxonomy.py, microsetta_public_api/models/tests/test_taxonomy.py
Removed the 10% filter as it was misguided, and upstream of reducing to the top N taxa
Now ranking after limiting to the top taxa
Removed "g__" as it's meaningless
=> BUG: filtering ranks rather differently from the proof of concept

ci/conda_requirements.yml, ci/pip_requirements.txt, microsetta_public_api/api/microsetta_public_api.yml, microsetta_public_api/api/taxonomy.py, microsetta_public_api/api/tests/implementation_tests/test_taxonomy.py, microsetta_public_api/api/tests/test_api.py, microsetta_public_api/models/_taxonomy.py, microsetta_public_api/models/tests/test_taxonomy.py, microsetta_public_api/repo/_taxonomy_repo.py, setup.py
This PR servers a python `Empress` object, which can be used to client side to render an empress display.
Fixes #81 Fixes #82
=> NEW Add empress for taxonomy

microsetta_public_api/server.py
Quick fix. I was running into issues with the empress json encoding numpy integers, so I patched through this encoder that should make sure all of the numpy ints are interpretted as python ints.
=> FIX make encoding safe for numpy ints
